---
title: "Testing"
author: "Rutuja"
date: "2024-04-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Imports

```{r}
library(tidyverse)
```


This is for tracing the bias in the transcription and replication data. I am going through all the processed and unprocessed data files and finding the source of the bias.

Reading in the replication data first. Hopefully this isnt inherently coming with biases.

```{r}
rep.dynamics <- read.csv("replication_data/clean_rep.csv")
rep <- rep.dynamics[, c("chr_num", "pos", "rep.sign")]
```


```{r}
head(rep.dynamics)
rep.dynamics %>% 
  ggplot() +
  geom_density(aes(x=ratio, color=as.character(rep.sign)))

table(rep.dynamics$rep.sign)
rm(rep.dynamics)
```


Starting with clean_data

```{r}
net <- read.csv("clean_data/net.csv")
```

```{r}
df <- net[, c("chr_num", "pos", "strand")]
df <- left_join(df, rep, by = c("chr_num", "pos"))
table(df$strand, df$rep.sign)
```

```{r}
rm(df)
rm(net)
```

Folder: data

```{r}
net.plus <- read.csv("data/net_plus.csv")
net.minus <- read.csv("data/net_minus.csv")
net.plus$strand <- "+"
net.minus$strand <- "-"
net <- bind_rows(net.plus, net.minus)
rm(net.plus)
rm(net.minus)
df <- net[, c("chr_num", "pos", "strand")]
df <- left_join(df, rep, by = c("chr_num", "pos"))
table(df$strand, df$rep.sign)
rm(df)
rm(net)
```

Folder: final_data

```{r}
net <- read.csv("final_data/d.csv")
net$strand <- ifelse(net$net_tot.minus > net$net_tot.plus, "-", 
                     ifelse(net$net_tot.minus < net$net_tot.plus, "+", "NA"))
table(net$strand, net$rep.strand.dip)
table(net$strand, net$rep.strand.hap)
rm(net)
```

Folder: net_mapped

```{r}
net <- read.csv("net_mapped/closest_net.csv")
df <- net[, c("chr_num", "pos", "strand")]
df <- left_join(df, rep, by = c("chr_num", "pos"))
table(df$strand, df$rep.sign)
rm(net)
rm(df)

net <- read.csv("net_mapped/double_net.csv")
df <- net[, c("chr_num", "pos", "strand")]
df <- left_join(df, rep, by = c("chr_num", "pos"))
table(df$strand, df$rep.sign)
rm(net)
rm(df)

net <- read.csv("net_mapped/weighted_net.csv")
df <- net[, c("chr_num", "pos", "strand")]
df <- left_join(df, rep, by = c("chr_num", "pos"))
table(df$strand, df$rep.sign)
rm(net)
rm(df)
```


```{r}
net <- read.csv("net_mapped/weighted_net.csv")
# df <- net[, c("chr_num", "pos", "strand")]
df <- left_join(net, rep, by = c("chr_num", "pos"))
table(df$strand, df$rep.sign)

df$total <- replace_na(df$total, 0)

df %>% ggplot() +
  geom_density(aes(x=total)) +
  facet_grid(rows=vars(rep.sign), cols=vars(strand))
```




